name: moodjar
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  flutter_gradient_colors: ^2.1.1
  animate_do: ^3.1.2
  flutter_animate: ^4.5.0
  glass_kit: ^3.0.0
  flutter_svg: ^2.0.9
  lottie: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.0
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
